spring.application.name=Campushelpdesk
spring.datasource.url=jdbc:mysql://localhost:3306/camphelpdesk
spring.datasource.username=root
spring.datasource.password=2005
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql=true
jwt.secret=AD505465FA89D6BC95712E6905476232FA803D347EB26B918067434971DE5BD2
jwt.expiration=1800000
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nostos.backend@gmail.com
spring.mail.password=fghnzlnkbeatkbia
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


